language: node_js

node_js:
  - 0.12
  - iojs
  - 4

sudo: false

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - npm install -g codeclimate-test-reporter
  - cat coverage/Chromium*/lcov.info >>coverage/lcov.info
  - codeclimate < coverage/lcov.info

addons:
  code_climate:
    repo_token: f159eec3f70f0484d592e32cd87160b251249591a1f8007bea22ac4b819ffe45

notifications:
  email:
    on_success: change
    on_failure: always
